apiVersion: v1
kind: ConfigMap
metadata:
  {{- include "krypton-lib-slim.metadata" (dict "ctx" . "component" "configMap") | nindent 2 }}
data:
  {{- .Values.config | default dict | toYaml | nindent 2 }}
