apiVersion: v1
kind: ConfigMap
metadata:
  {{- include "krypton-lib.metadata" (dict "ctx" . "component" "configmap") | nindent 2 }}
data:
  {{- (.Values.config | default dict).data | default dict | toYaml | nindent 2 }}
